spring:
  main:
    banner-mode: off
  security:
    user:
      name: admin
      password: admin
  datasource:
    # MySQL config test
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MANAHOTEL_DB
    username: root
    password: 123456
    hikari:
      poolName: Hikari
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hotelsystem00@gmail.com
    password: vsjpxutvricoknsg

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true





